parameters:
#    digitalshift_mailbox_client.example.class: Digitalshift\MailboxClientBundle\Example

services:
#    digitalshift_mailbox_client.example:
#        class: %digitalshift_mailbox_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
